import { Inter } from "next/font/google";
import "./globals.css";

import Script from 'next/script';

<Script
  src="https://unpkg.com/flowbite@1.3.3/dist/flowbite.js"
  strategy="beforeInteractive"
/>

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "eFooDi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
