import "./globals.css";
import "@fontsource/dm-sans";
import Script from 'next/script';

<Script
  src="https://unpkg.com/flowbite@1.3.3/dist/flowbite.js"
  strategy="beforeInteractive"
/>

export const metadata = {
  title: "eFooDi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
